# Generated by Django 5.1.5 on 2025-02-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protons', models.IntegerField()),
                ('neutrons', models.IntegerField()),
                ('electrons', models.IntegerField()),
                ('element', models.CharField(max_length=50)),
                ('stable', models.BooleanField()),
            ],
        ),
    ]
